dist: xenial
sudo: required
language: c
compiler:
  - gcc
branches:
  only:
    - master
    - dev
before_install:
  - pwd
  - git clone https://github.com/akheron/jansson
  - cd jansson
  - autoreconf -i
  - ./configure --prefix=/usr
  - cd ../

  - pwd
  - git clone -b $TRAVIS_BRANCH https://github.com/gonapps-org/libgenc
  - cd libgenc
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../

  - pwd
  - git clone -b $TRAVIS_BRANCH https://github.com/gonapps-org/libfastdl
  - cd libfastdl
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../

install:
  - sudo apt-get install -y uthash-dev libcmocka-dev

  - pwd
  - cd jansson
  - make
  - make check
  - sudo make install
  - cd ../

  - pwd
  - cd libgenc/build
  - make
  - sudo make install
  - cd ../../

  - pwd
  - cd libfastdl/build
  - make
  - sudo make install
  - cd ../../

before_script:
  - cmake -version
  - make --version 
  - gcc --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_WITH_COVERAGE=ON ..

script: make && ctest -V
after_success:
  - bash <(curl -s https://codecov.io/bash)
